/* gvSIG. Geographic Information System of the Valencian Government
 *
 * Copyright (C) 2007-2008 Infrastructures and Transports Department
 * of the Valencian Government (CIT)
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA  02110-1301, USA.
 *
 */
package org.gvsig.tools.observer;

import org.gvsig.tools.visitor.Visitable;

/**
 * Interface for notifications generated by a {@link ComplexObservable} when the
 * {@link ComplexObservable#beginComplexNotification()} method is used.
 * <p>
 * Once the {@link ComplexObservable#endComplexNotification()} is called, if an
 * observer is a {@link ComplexObserver}, it will be notified with a
 * {@link ComplexNotification}, instead of each of the individual notifications.
 * </p>
 * 
 * @author gvSIG Team
 * @version $Id$
 */
public interface ComplexNotification extends Visitable {
    // Nothing to add
}
